language: node_js
env:
  global:
    secure: L2FtneI+bteDesuXik1/AC5ZM6y1e3Zmk8kwyGl/ZeBfVqnnWuK4fqw5Y8B6owvPen905slP69zwGyt14VYTExdZ8x53fa7tm9bZ6LSUIkqDiuzYsXytWu3tiBhao5lXG8l2LbcOoQqgbjQF3qUMynPNe7rhrNDRkxpFmdDtDqgJFJBSRZB22lYFot1jcyuYNuWIQiM8qRCa5X6ijQgFKy4iNHbRHQ0Oi4wn386LQM7neYpDnUnP6uR5i1J+3c7b7NOJHxdWT8tIp0dniQfQqwRtfovPUEqOv+YMZ1yCqvvi5boLThd1n+95NIS5mo/KBizY6BpS0pYbCNjnyXV/thlkl64yQOFFE5mN89XeNlW3omuQNYSaUY/dGgweiBm27qkE3AI5kIfyAzW8sS/Hy3ckW72Jp/XQv8KeuikRMzXQ/DBUKqRZ7TnD5qCljFU5MDc/Ekva0G3j/9rqc5iWLInyxOyJQU7PSBBraQv3E281pHjst83AG9I4IeQtAD98wzL/0+0lOT3B0dbNJfjhHgx+TIuJFS1xaDJIW3VlqPeia/3R5GKOzy2JO0TD0xN/QkT8Uwf3T0yBkJU+2mWXb6hkYWgViDbI6PS9HyLQ/6oM8opNvMXoE5BFXpyUyQcPGqM8Tr+Hi7B/Gh1RnWgyjHsKMiO20AIKtyOR9PMpajw=


sudo: required

services:
  - docker

before_install:
# modify submodule URLs so travis fetches over HTTPS not SSH
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- make
- docker build -t exitnode .

script:
- DEBUG=1 ./bin/bengomesh-docker digitalocean-exitnode test
